name: Deploy to Cloud Run

on:
  push:
    branches:
      - master
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: asia-northeast1
  # project-name but it can be anything you want
  REPOSITORY: nx-gha-cgp
  SERVICE: my_service_name  # TODO: update Cloud Run service name
  REGION: asia-northeast1
jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate with Google Cloud
      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}"

      # NOTE: Alternative option - authentication via credentials json
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"

      # # Setup gcloud CLI/SDK
      # - name: Set up Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v2

      # - name: Authorize Docker push
      #   run: gcloud auth configure-docker

      # - name: Build and tag the docker image
      #   run: |-
      #     docker build . --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

      # - name: Push the image to the Google Container Registry (GCR)
      #   run: |-
      #     docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA


      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If using a pre-built image, update the image name here
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
          # NOTE: You can also set env variables here:
          #  env_vars: |
          #  NODE_ENV=production
          #  TOKEN_EXPIRE=6400

      # - name: Deploy
      #   run: |-
      #     gcloud run deploy $REPO_NAME \
      #     --region $REGION \
      #     --image gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
      #     --platform "managed" \
      #     --port 3000 \
      #     --allow-unauthenticated \
      #     --quiet
